name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright Browsers
      run: |
        source .venv/bin/activate
        python -m playwright install chrome --with-deps

    - name: create enviornment file from workflow
      run: |
        set -x
        ENV_FILE=".env"
        echo "BASE_URL=${BASE_URL}" >> "$ENV_FILE"
        set +x

    - name: Run tests with Pytest
      run: |
        source .venv/bin/activate
        pytest Ultimateqa/tests -n auto --maxfail=3 --tb=short